<<<<<<< HEAD
=======
# pyproject.toml
>>>>>>> projeto-dundie-rewards/main
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q -vv"
testpaths = [
    "tests",
    "integration",
]

<<<<<<< HEAD

[tool.flake8]
exclude = [".venv", "build", ".vscodelocal", "migrations"]
=======
[tool.flake8]
exclude = [".venv", "build"]
>>>>>>> projeto-dundie-rewards/main
max-line-length = 79
# extend-ignore = "W293,"

[tool.black]
line-length = 79
target-version = ["py36", "py37"]
exclude = '''
/(
    \.eggs
  | \.git
  | \.venv
  | _build
  | build
  | dist
  | migrations
)/
'''
<<<<<<< HEAD

=======
>>>>>>> projeto-dundie-rewards/main
[tool.isort]
profile = "black"
src_paths = ["dundie", "tests", "integration"]
multi_line_output = 3  # VHI
<<<<<<< HEAD
line_length = 79
force_grid_wrap = 0
use_parentheses = true
include_trailing_comma = true
=======
>>>>>>> projeto-dundie-rewards/main
