# .github/workflows/main.yml
name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  lint:
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.10']
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install Project
        run: pip install '.[test]'
      - name: Look for style erros
        run: pflake dundie

  tests:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10']
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install Project
        run: pip install '.[test,dev]'
      - name: Run tests
        run: pytest -v --junitxml=text-result.xml
      - name: publish junit results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          file: test-result.xml
          check_name: Test Result (Python ${{matrix.python-version}})
